{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    limits.cpu: {{ .Values.namespace.limits.cpu }}
    limits.memory: {{ .Values.namespace.limits.memory }}
    limits.ephemeral-storage: {{ .Values.namespace.limits.ephemeral_storage }}
    requests.cpu: {{ .Values.namespace.requests.cpu }}
    requests.memory: {{ .Values.namespace.requests.memory }}
    requests.ephemeral-storage: {{ .Values.namespace.requests.ephemeral_storage }}
{{- end }}
