apiVersion: v1
kind: Service
metadata:
  name: {{ include "ciroh.fullname" . }}
  labels:
{{ include "ciroh.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # - name: http
      # port: {{ .Values.service.port }}
      # targetPort: {{ .Values.service.port }}      
  selector:
    app.kubernetes.io/name: {{ include "ciroh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

