apiVersion: v2
name: ciroh
appVersion: '0.0.1'
description: 'Tethys portal for CIROH'
type: application
version: 0.1.6
dependencies:
  - name: 'postgis'
    repository: 'oci://ghcr.io/romer8'
    version: '*'
  - name: 'geoserver'
    repository: 'oci://ghcr.io/romer8/geoserver'
    version: '*'
    condition: geoserver.enabled
  - name: 'thredds'
    repository: 'https://aquaveo.github.io/misc-helm-charts'
    version: '*'
    condition: thredds.enabled
  - name: 'redis'
    repository: 'https://charts.bitnami.com/bitnami'
    version: '*'
    condition: redis.enabled
  - name: 'djangocms'
    repository: 'https://aquaveo.github.io/django-cms-quickstart'
    version: '*'
    condition: djangocms.enabled
