apiVersion: v2
name: ciroh
appVersion: '0.0.1'
description: 'Tethys portal for CIROH'
type: application
version: 0.1.6
dependencies:
  - name: 'postgis'
    repository: 'https://raw.githubusercontent.com/romer8/misc-helm-charts/master/docs'
    version: '*'
  - name: 'gs-cloud'
    repository: 'https://raw.githubusercontent.com/romer8/misc-helm-charts/master/docs'
    version: '*'
    condition: gs-cloud.enabled
  - name: 'thredds'
    repository: 'https://raw.githubusercontent.com/romer8/misc-helm-charts/master/docs'
    version: '*'
    condition: thredds.enabled
  - name: 'redis'
    repository: 'https://charts.bitnami.com/bitnami'
    version: '*'
    condition: redis.enabled
  - name: 'djangocms'
    repository: 'https://aquaveo.github.io/django-cms-quickstart'
    version: '*'
    condition: djangocms.enabled
