apiVersion: v2
name: ciroh
appVersion: '0.0.1'
description: 'Tethys portal for CIROH'
type: application
version: 0.1.6
dependencies:
  - name: 'postgis'
    repository: 'oci://ghcr.io/romer8'
    version: '*'
  - name: 'geoserver'
    repository: 'oci://ghcr.io/romer8'
    version: '*'
  - name: 'thredds'
    repository: 'oci://ghcr.io/aquaveo'
    version: '*'
  - name: 'redis'
    repository: 'https://charts.bitnami.com/bitnami'
    version: '*'
  - name: 'djangocms'
    repository: 'oci://ghcr.io/romer8'
    version: '*'
