target-branch: aws-portal
chart-dirs:
  - ../../helm/ciroh
helm-extra-args: --timeout 600s
check-version-increment: false
upgrade: true
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - aquaveo=oci://ghcr.io/aquaveo
