version: '3.1'
services:
  db:
    image: postgis/postgis:15-3.3
    networks:
      - 'internal'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=please_dont_use_default_passwords
  web:
    image: "${TEST_IMAGE}"
    command: "${TEST_COMMAND}"
    depends_on:
      - 'db'
      # - 'thredds'
      # - 'redis'
    networks:
      - 'internal'
      - 'external'
    ports:
      - '80:80'
    env_file:
      - web.env
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 20s      
networks:
  internal:
    internal: true
  external:
