version: '3.1'
services:
  db:
    image: postgis/postgis:15-3.3
    networks:
      - 'internal'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=please_dont_use_default_passwords
  web:
    image: "${TEST_IMAGE}"
    command: run.sh --test
    depends_on:
      - 'db'
    networks:
      - 'internal'
      - 'external'
    ports:
      - '80:80'
    env_file:
      - web.env
networks:
  internal:
    internal: true
  external:
