version: '3.1'
services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    networks:
      - 'internal'
    ports:
      - '5432:5432'
    env_file:
      - ./env/db.env
    volumes:
      - ./data/psql:/var/lib/postgresql/data

  thredds:
    image: tethysplatformuploader/thredds-docker:4.6.20-SNAPSHOT
    restart: always
    networks:
      - 'internal'
      - 'external'
    ports:
      - '8080:8080'
    env_file:
      - ./env/thredds.env
    volumes:
      - ./data/thredds/:/usr/local/tomcat/content/thredds
      - ./logs/thredds/tomcat/:/usr/local/tomcat/logs/
      - ./logs/thredds/thredds/:/usr/local/tomcat/content/thredds/logs/
      - ./config/thredds/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./config/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./config/thredds/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ./config/thredds/wmsPalettes/:/usr/local/tomcat/content/thredds/wmsPalettes/
      - ./data/tethys/thredds_data/:/usr/local/tomcat/content/thredds/public/thredds_data

  redis:
    image: redis:latest
    restart: always
    networks:
      - 'external'
    ports:
      - '6379:6379'

  geoserver:
    image: tethysplatform/geoserver:latest
    restart: always
    networks:
      - 'internal'
      - 'external'
    ports:
      - '8181:8181'
      - '8081:8081'
      - '8082:8082'
      - '8083:8083'
      - '8084:8084'
    env_file:
      - ./env/geoserver.env
    volumes:
      - ./data/geoserver/:/var/geoserver/data

  web:
    image: tethys-portal-docker:latest
    build: 
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    depends_on:
      - 'db'
      - 'thredds'
      - 'redis'
    networks:
      - 'internal'
      - 'external'
    ports:
      - '80:80'
    env_file:
      - ./env/web.env
    volumes:
      - ./data/tethys:/var/lib/tethys_persist
      - ./logs/tethys:/var/log/tethys
      - ./config/tethys/portal_changes.yml:/usr/lib/tethys/portal_changes.yml
networks:
  internal:
    internal: true
  external:
