remote: origin
target-branch: aws-portal
chart-dirs:
  - charts
helm-extra-args: --timeout 600s
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - misc-helm-chart=https://aquaveo.github.io/misc-helm-charts
  - romero8=oci://ghcr.io/romer8
