remote: origin
target-branch: aws-portal
chart-dirs:
  - charts
helm-extra-args: --timeout 600s
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - misc-helm-chart=oci://ghcr.io/aquaveo
  - romero8=oci://ghcr.io/romer8
