remote: origin
target-branch: aws-portal
chart-dirs:
  - charts
helm-extra-args: '--timeout 600s -f charts/ciroh/ci/values-ci.yaml'
check-version-increment: false
validate-maintainers: false
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - misc-helm-charts=https://raw.githubusercontent.com/aquaveo/misc-helm-charts/master/docs/
  - django-cms-quickstart=https://aquaveo.github.io/django-cms-quickstart
