remote: origin
target-branch: aws-portal
chart-dirs:
  - charts
helm-extra-args: --timeout 600s
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - misc-helm-charts=https://raw.githubusercontent.com/aquaveo/misc-helm-charts/master/docs/
  - django-cms-quickstart=https://aquaveo.github.io/django-cms-quickstart
