apps:
name: None
settings:
  CHANNEL_LAYERS:
    default:
      BACKEND: channels_redis.core.RedisChannelLayer
      CONFIG:
        hosts:
        - redis://localhost:6379
  DATABASES:
    default:
      DIR: psql
      ENGINE: django.db.backends.postgresql
      HOST: localhost
      NAME: tethys_platform
      PASSWORD: pass
      PORT: 5436
      USER: tethys_super
  SECRET_KEY: Y8VPTDqgHsrblKlIOuJhUTfNOVOGP5liTHu1p3Pz5HZ41YdC9g
site_settings:
  CUSTOM_STYLES: {}
  CUSTOM_TEMPLATES: {}
  GENERAL_SETTINGS: {}
  HOME_PAGE: {}
version: 2.0
