apps:
  water_data_explorer:
    services:
      persistent:
        catalog_db: tethys_postgis
      spatial: {}
      dataset: {}
      wps: {}
      custom_settings: {}
  metdataexplorer:
    services:
      persistent:
        thredds_db: tethys_postgis
      spatial: {}
      dataset: {}
      wps: {}
      custom_settings:
        disclaimer_header: 'CIROH TERMS OF SERVICE'
        disclaimer_message: 'The MDE is a tethys application under the MIT license'
  ggst:
    services:
      persistent: {}
      spatial: {}
      dataset: {}
      wps: {}
      custom_settings:
        grace_thredds_directory: '/thredds/catalog/ciroh_data/tethys/ggst_thredds_directory/catalog.xml'
        grace_thredds_catalog: '/thredds_data/tethys/ggst_thredds_directory'
        global_output_directory: '/usr/lib/tethys'
        earthdata_username: 'byugrace'
        earthdata_pass: 'byuGRACE1'
        conda_python_path: '{{ CONDA_HOME }} + "/envs/" + {{ CONDA_ENV_NAME }} + "/bin/python"'
  swe:
    services:
      persistent: {}
      spatial:
        thredds_service: tethys_thredds
      dataset: {}
      wps: {}
      custom_settings: {}
