proxy_apps:
  CIROH JupyterHub:
    back_url: web
    description: Proxy app for the CIROH JupyterHub
    enabled: true
    endpoint: https://jupyterhub.cuahsi.org/hub/login
    logo_url: /static/ciroh_theme/images/jupyterhub.png
    name: CIROH JupyterHub
    open_in_new_tab: true
    order: 1
    show_in_apps_library: true
    tags: CUAHSI
  HydroShare:
    back_url: web
    description: Proxy app for the Hydroshare app
    enabled: true
    endpoint: https://www.hydroshare.org/home/
    logo_url: /static/ciroh_theme/images/HydroShare.png
    name: HydroShare
    open_in_new_tab: true
    order: 2
    show_in_apps_library: true
    tags: CUAHSI
  OWP NWM Map Viewer:
    back_url: web
    description: Proxy app for Office in Water Prediction
    enabled: true
    endpoint: https://water.noaa.gov/map
    logo_url: /static/ciroh_theme/images/owp.png
    name: OWP NWM Map Viewer
    open_in_new_tab: true
    order: 0
    show_in_apps_library: true
    tags: '"NOAA", "Ciroh", "Office of Water Prediction"'
