variable "region" {}
variable "profile" {}
variable "cluster_name" {}
variable "app_name" {}
variable "helm_chart" {}
variable "helm_repo" {}
variable "helm_values_file" {}
variable "environment" {}
variable "create_elastic_ips" {}
