{{- range $key, $definition := .Values.nfs }}
# PVC {{ print $key }}-claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$definition.pvcname}}
spec:
  accessModes:
    - {{ $definition.accessModes }}
  resources:
    requests:
      storage: {{$definition.storage}}
  volumeName: {{$definition.pvname}}
  {{- if and $definition.storageClass.storageClassName .Values.storageClass.enabled }}
  storageClassName: {{ $definition.storageClass.storageClassName | quote }}
  {{- end }}
{{- end }}
