{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ciroh.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ciroh.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: alb
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
          - path: "/geoserver"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.geoserver.fullnameOverride }}
                port: 
                  number: 8181
          - path: "/thredds"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.thredds.fullnameOverride }}
                port: 
                  number: 8080                  

  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-static
  labels:
{{ include "ciroh.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
          - path: "/static"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  name: http
  {{- end }}
{{- end }}
