apiVersion: v1
kind: Service
metadata:
  name: {{ include "ciroh.fullname" . }}
  labels:
{{ include "ciroh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # {{- include "ciroh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ciroh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

