name: Lint and Test Charts

on:
  push:
    branches:
      - aws-portal

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./.github/config/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ./.github/config/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: ${{ needs.list-changed.outputs.changed }} == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ./.github/config/ct.yaml
        if: ${{ needs.list-changed.outputs.changed }} == 'true'
