name: test_deployment

on:
  push:
    branches:
      - '*'
env:
  DOCKER_HUB_ORG: gioelkin
  DOCKER_REPO: tethysapp-ciroh-portal

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deployment-workflow:
    uses: ./.github/workflows/helm_deploy.yml
    with:
      dry-run: true
