name: push_commits_no_tag

# Push to docker hub if no tag has been created.
on:
  push:
    branches:
      - 'aws-portal'

env:
  TEST_IMAGE: gioelkin/tethys_portal:dev_${GITHUB_SHA}
  IMAGE_TAG: dev_5c021e8bc75e84947231883896cae575e9b2d36e
  DOCKER_HUB_ORG: gioelkin
  DOCKER_REPO: tethys_portal
  MAX_NUMBER_IMAGE: 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_BUILDER_USERNAME }} -p ${{ secrets.DOCKER_BUILDER_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ env.DOCKER_HUB_ORG }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
      - name: Run Salt Test
        run: |
          export "TEST_IMAGE=${{ env.DOCKER_HUB_ORG }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          export "TEST_COMMAND=run.sh --test" >> $GITHUB_ENV
          docker compose -f .github/scripts/docker-compose-ci.yml up
          export "TEST_COMMAND=run.sh" >> $GITHUB_ENV
          docker compose -f .github/scripts/docker-compose-ci.yml up
      - name: List container
        run: |
          docker ps -a
      - name: Test
        run: |
          sleep 120
          docker run --network container:web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80
