name: push_commits_no_tag

# Push to docker hub if no tag has been created.
on:
  push:
    branches:
      - 'aws-portal'

env:
  TEST_IMAGE: gioelkin/tethys_portal:dev_${GITHUB_SHA}
  IMAGE_TAG: dev_5c021e8bc75e84947231883896cae575e9b2d36e
  DOCKER_HUB_ORG: gioelkin
  DOCKER_REPO: tethys_portal
  MAX_NUMBER_IMAGE: 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis
        env:
          POSTGRES_HOST: postgis
          POSTGRES_PASSWORD: please_dont_use_default_passwords
          POSTGRES_DB: tethys_postgis
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_BUILDER_USERNAME }} -p ${{ secrets.DOCKER_BUILDER_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ env.DOCKER_HUB_ORG }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
      - name: Run Salt Test
        run: |
          docker run --rm --name ciroh_portal --network ${{ job.services.postgis.network }} --env-file .github/scripts/web.env ${{ env.DOCKER_HUB_ORG }}/${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }} /bin/bash -c "cd /usr/lib/tethys && source ./run.sh --test"
